service: notes-app-api

# Create optimized packages (per function, better UX)
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: us-west-2
  # These environment variables are available to ƛ functions
  # under process.env
  environment:
    tableName: notes
# Lambdas granted permission to access DynamoDB
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-west-2:*:*"

functions:
# API endpoint, calls /create.js
  create:
      handler: create.main
      events:
        - http:
            path: notes
            method: post
            cors: true
            authorizer: aws_iam